version: '3'

services:
  frontend:
    build: frontend
    ports:
      - 8501:8501
    depends_on:
      - api
    volumes:
        - ./storage:/storage
  api:
    build: api
    ports:
      - 8080:8080
    volumes:
      - ./storage:/storage